### ISSUE TITLE
C Make `projects` optional

### ISSUE THREAD

**Issue by cmutel** [brightway-lca/brightway2-data#97]
Projects as separate subdirectories is not a useful concept for all databases or organizations. Rather, they are an implementation detail of the current database backend structure (separate SQLite databases in subdirectories).

Specific tasks:

- [x] C1 [Separate project handling into a separate library](https://github.com/brightway-lca/brightway2-data/issues/98)
- [ ] C2 [Adapt testing framework to not rely on projects](https://github.com/brightway-lca/brightway2-data/issues/99)
- [ ] C3 [Provide separate test decorators for backends which do and do not use the projects concept](https://github.com/brightway-lca/brightway2-data/issues/100)

**Comment by cmutel** [comment]
Project handling is now in https://github.com/brightway-lca/brightway_projects.
